apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/mysql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-pv
  storageClassName: standard

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sparklmsdb-deployment 
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: sparklms-mysqldb
  template:
    metadata:
      labels:
        app: sparklms-mysqldb
    spec:
      containers:
        - name: sparklmsdb
          image: mysql:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ''
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: MYSQL_USER
              value: 'lmsadmin'
            - name: MYSQL_PASSWORD
              value: 'lmspass'
            - name: MYSQL_DATABASE
              value: 'sparklmsdb'

          ports:
            - containerPort: 3306 
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: sparklms-mysqldb
  ports:
  - protocol: TCP
    port: 3306 
    targetPort: 3306
  type: ClusterIP


