---
- name: Write service file and Deploy Java application
  hosts: ec2
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Copy JAR Artifact to remote host
      copy:
        src: "{{item}}"
        dest: /tmp/
      with_fileglob:
        - "{{ playbook_dir }}/../target/*.jar"

    - name: Write service file
      copy:
        content: |
          [Unit]
          Description=Spark LMS Runner

          [Service]
          User=ec2-user
          WorkingDirectory=/tmp
          ExecStart=/usr/bin/java -jar spark-lms-0.0.1-SNAPSHOT.jar
          SuccessExitStatus=143
          TimeoutStopSec=10
          Restart=on-failure
          RestartSec=30

          [Install]
          WantedBy=multi-user.target
        dest: /usr/lib/systemd/system/sparklms.service

    - name: Create symlink in /etc/systemd/system
      file:
        src: /usr/lib/systemd/system/sparklms.service
        dest: /etc/systemd/system/multi-user.target.wants/sparklms.service
        state: link

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and Start the service
      ansible.builtin.service:
        name: sparklms
        state: restarted
        enabled: yes

      