---
- name: Update Inventory file with new IP
  hosts: localhost
  become: yes

  tasks:
    - name: Replace mysql-service:3306/sparklmsdb
      replace:
        path: "{{ playbook_dir }}/../src/main/resources/application.properties"
        regexp: 'mysql-service:3306/sparklmsdb'
        replace: 'team-kernull-rds.cjldgoxvvwoc.us-west-2.rds.amazonaws.com:3306/saminsparklms'

    - name: Replace spring.datasource.username
      replace:
        path: "{{ playbook_dir }}/../src/main/resources/application.properties"
        regexp: 'spring.datasource.username = root'
        replace: 'spring.datasource.username = samin'

    - name: Replace spring.datasource.password
      replace:
        path: "{{ playbook_dir }}/../src/main/resources/application.properties"
        regexp: 'spring.datasource.password ='
        replace: 'spring.datasource.password = 12345678'